name: 'soccer_challenge'
version: '1.0.0'
config-version: 2

profile: 'soccer_challenge'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

# Default materialization; override per-model/folder as you see fit.
models:
  soccer_challenge:
    +materialized: view
